Repository juspay/superposition, pull requests merged in 2024-05, with the labels that each got.

#44 feat: reducing context tool
  crates/context_aware_config/src/api/config/handlers.rs
  crates/context_aware_config/src/api/context/handlers.rs
  crates/context_aware_config/src/api/context/mod.rs
Labels: priority

#72 fix: row numbering in paginated table
  crates/frontend/src/components/pagination/pagination.rs
  crates/frontend/src/components/table/table.rs
  crates/frontend/src/components/table/types.rs
  crates/frontend/src/pages/experiment_list/experiment_list.rs
  crates/frontend/src/pages/function/function_list.rs
Labels: UI

#75 chore: Add a new check ensure .editorconfig rules are honored
  .editorconfig
  .gitignore
  crates/context_aware_config/migrations/2023-10-16-133815_context-aware-config-init/down.sql
  crates/context_aware_config/migrations/2023-10-16-133815_context-aware-config-init/up.sql
  crates/experimentation_platform/migrations/2023-10-16-134612_experimentation-init/down.sql
  crates/experimentation_platform/migrations/2023-10-16-134612_experimentation-init/up.sql
  crates/experimentation_platform/migrations/2024-01-18-063937_audit_log_partitions/up.sql
  crates/frontend/src/pages/function/function_create.rs
  flake.lock
  flake.nix
  nix/pre-commit.nix
  postman/experimentation-platform/Get Experiment/request.json
Labels: priority

#73 feat: Add JP version and regex operations in jsonlogic
  Cargo.lock
  Cargo.toml
  clients/js/index.js
  clients/js/src/index.ts
  clients/js/src/utils/operations.ts
Labels: priority

#63 feat: delete support for default config in UI
  crates/frontend/src/api.rs
  crates/frontend/src/components/alert/mod.rs
  crates/frontend/src/components/context_form/utils.rs
  crates/frontend/src/components/default_config_form/utils.rs
  crates/frontend/src/components/dimension_form/utils.rs
  crates/frontend/src/components/experiment_form/utils.rs
  crates/frontend/src/components/function_form/utils.rs
  crates/frontend/src/pages/default_config/default_config.rs
  crates/frontend/src/utils.rs
Labels: priority, UI

#79 fix: stricter validation for key names in default config
  Cargo.lock
  Cargo.toml
  crates/caclang/Cargo.toml
  crates/context_aware_config/Cargo.toml
  crates/context_aware_config/src/api/default_config/handlers.rs
  postman/cac/Default Config/Default-Config Add Key Failure-Invalid-Regex/.event.meta.json
  postman/cac/Default Config/Default-Config Add Key Failure-Invalid-Regex/event.test.js
  postman/cac/Default Config/Default-Config Add Key Failure-Invalid-Regex/request.json
  postman/cac/Default Config/Default-Config Add Key Failure-Invalid-Regex/response.json
Labels: priority

#78 feat: Add local storage support
  Cargo.lock
  Cargo.toml
  crates/context_aware_config/src/api/config/handlers.rs
  crates/frontend/Cargo.toml
  crates/frontend/src/pages/ContextOverride/context_override.rs
  crates/frontend/src/pages/default_config/default_config.rs
  crates/frontend/src/utils.rs
Labels: priority, UI
