Repository juspay/superposition, pull requests merged in 2024-06, with the labels that each got.

#10 add snapshot while context , default configs updates
  Cargo.lock
  crates/context_aware_config/Cargo.toml
  crates/context_aware_config/migrations/2024-04-22-122806_config_verions/down.sql
  crates/context_aware_config/migrations/2024-04-22-122806_config_verions/up.sql
  crates/context_aware_config/src/api/config/handlers.rs
  crates/context_aware_config/src/api/config/mod.rs
  crates/context_aware_config/src/api/config/types.rs
  crates/context_aware_config/src/api/context/handlers.rs
  crates/context_aware_config/src/api/context/types.rs
  crates/context_aware_config/src/api/default_config/handlers.rs
  crates/context_aware_config/src/db/models.rs
  crates/context_aware_config/src/db/schema.patch
  crates/context_aware_config/src/db/schema.rs
  crates/context_aware_config/src/helpers.rs
  crates/context_aware_config/tests/cac_tests.rs
  crates/experimentation_platform/Cargo.toml
  crates/experimentation_platform/src/api/experiments/handlers.rs
  crates/experimentation_platform/src/api/experiments/types.rs
  crates/experimentation_platform/src/db/models.rs
  crates/service_utils/Cargo.toml
  crates/service_utils/src/helpers.rs
  crates/service_utils/src/service/types.rs
  crates/superposition/src/main.rs
  postman/cac/.meta.json
  postman/cac/config/Get Config/event.test.js
Labels: priority

#91 feat: Support relative path for frontend
  crates/frontend/src/utils.rs
Labels: enhancement

#76 fix: updated instruction for local setup in mac OS
  .env.example
  docs/setup.md
  makefile
Labels: priority

#70 fix: display order of override keys
  crates/frontend/src/components.rs
  crates/frontend/src/components/context_card.rs
  crates/frontend/src/components/context_form.rs
  crates/frontend/src/components/default_config_form.rs
  crates/frontend/src/components/dimension_form.rs
  crates/frontend/src/components/dropdown.rs
  crates/frontend/src/components/experiment_form.rs
  crates/frontend/src/components/experiment_form/types.rs
  crates/frontend/src/components/experiment_form/utils.rs
  crates/frontend/src/components/override_form.rs
  crates/frontend/src/components/variant_form.rs
  crates/frontend/src/pages/context_override.rs
  crates/frontend/src/pages/custom_types.rs
  crates/frontend/src/pages/default_config.rs
  crates/frontend/src/pages/experiment.rs
  crates/frontend/src/pages/function.rs
  crates/frontend/src/pages/function/function_create.rs
  crates/frontend/src/pages/function/function_list.rs
  crates/frontend/src/pages/home.rs
  crates/frontend/src/types.rs
  crates/frontend/src/utils.rs
Labels: priority, UI

#127 Use jsonlogic's partial_apply for config and experiment filtering
  Cargo.lock
  Cargo.toml
  clients/haskell/hs-cac-client/src/Client.hs
  clients/haskell/hs-cac-client/src/Main.hs
  clients/haskell/hs-exp-client/src/Client.hs
  clients/haskell/hs-exp-client/src/Main.hs
  crates/cac_client/src/interface.rs
  crates/cac_client/src/lib.rs
  crates/context_aware_config/Cargo.toml
  crates/context_aware_config/src/api/config/handlers.rs
  crates/context_aware_config/src/api/config/helpers.rs
  crates/experimentation_client/src/interface.rs
  crates/experimentation_client/src/lib.rs
  headers/libcac_client.h
  headers/libexperimentation_client.h
Labels: priority

#99 fix: parse type when submitting overrides, not on input
  crates/frontend/src/components/override_form.rs
Labels: priority

#135 fix: allow positive i32 number for dimension priority in dimension create
  crates/context_aware_config/src/api/dimension/handlers.rs
  crates/context_aware_config/src/api/dimension/types.rs
  crates/frontend/src/components/dimension_form.rs
  crates/frontend/src/components/dimension_form/types.rs
  crates/frontend/src/pages/dimensions.rs
Labels: P0

#134 fix: handled parsing for multiple possible types
  crates/frontend/src/utils.rs
Labels: P0
