Repository juspay/superposition, pull requests merged in 2025-03, with the labels that each got.

#432 feat: Added support for completions in monaco editor.
  Cargo.lock
  crates/frontend/Cargo.toml
  crates/frontend/src-js/utils.js
  crates/frontend/src/components/default_config_form.rs
  crates/frontend/src/components/dimension_form.rs
  crates/frontend/src/components/input.rs
  crates/frontend/src/components/monaco_editor.rs
  crates/frontend/src/components/type_template_form.rs
  nix/rust.nix
Labels: enhancement, UI

#407 fix: horizontal scroll
  crates/frontend/src/components/context_card.rs
  crates/frontend/src/components/experiment.rs
  crates/frontend/src/components/table.rs
  crates/frontend/src/components/table/types.rs
  crates/frontend/src/pages/config_version_list.rs
  crates/frontend/src/pages/custom_types.rs
  crates/frontend/src/pages/default_config.rs
  crates/frontend/src/pages/dimensions.rs
  crates/frontend/src/pages/experiment_list.rs
  crates/frontend/src/pages/experiment_list/utils.rs
  crates/frontend/src/pages/function/function_list.rs
  crates/frontend/src/pages/function/utils.rs
  crates/frontend/src/pages/organisations.rs
  crates/frontend/src/pages/workspace.rs
  crates/frontend/styles/tailwind.css
Labels: priority, UI

#416 feat: add key filter for default config
  crates/context_aware_config/src/api/default_config/handlers.rs
  crates/frontend/src/api.rs
  crates/frontend/src/pages/context_override.rs
  crates/frontend/src/pages/default_config.rs
  crates/frontend/src/pages/experiment.rs
  crates/frontend/src/pages/experiment_list.rs
  crates/superposition_types/src/api.rs
  crates/superposition_types/src/api/default_config.rs
Labels: UI

#435 fix: Params being sent in resolve page
  crates/frontend/src/logic.rs
Labels: bug, priority, UI, P0

#436 fix: z-index of delete modal
  crates/frontend/src/components/delete_modal.rs
Labels: bug, priority, UI, P0, quick win

#439 fix: Default value for dimensions while using in operator
  crates/frontend/src/logic.rs
Labels: enhancement, priority, UI, P0, quick win

#397 feat : Create Experiments From Overrides
  crates/frontend/src/components/context_card.rs
  crates/frontend/src/components/experiment_form.rs
  crates/frontend/src/pages/context_override.rs
  crates/frontend/src/pages/experiment.rs
  crates/frontend/src/pages/experiment_list.rs
  crates/frontend/src/types.rs
Labels: UI, P0

#424 feat: experiment filters in UI
  Cargo.lock
  crates/experimentation_platform/src/api/experiments/handlers.rs
  crates/experimentation_platform/src/api/experiments/types.rs
  crates/frontend/src/components/button.rs
  crates/frontend/src/components/context_form/utils.rs
  crates/frontend/src/components/experiment_form/utils.rs
  crates/frontend/src/components/input.rs
  crates/frontend/src/logic.rs
  crates/frontend/src/pages/experiment_list.rs
  crates/frontend/src/pages/experiment_list/utils.rs
  crates/frontend/src/pages/home.rs
  crates/frontend/src/types.rs
  crates/frontend/tailwind.config.js
  crates/superposition_types/Cargo.toml
  crates/superposition_types/src/database/models/experimentation.rs
Labels: UI
