Repository juspay/superposition, pull requests merged in 2025-04, with the labels that each got.

#443 feat: add autocomplete functions
  Cargo.lock
  crates/context_aware_config/Cargo.toml
  crates/context_aware_config/src/api/context/helpers.rs
  crates/context_aware_config/src/api/functions.rs
  crates/context_aware_config/src/api/functions/handlers.rs
  crates/context_aware_config/src/validation_functions.rs
  crates/frontend/src-js/utils.js
  crates/frontend/src/components/function_form.rs
  crates/frontend/src/components/function_form/types.rs
  crates/frontend/src/components/function_form/utils.rs
  crates/frontend/src/pages/function.rs
  crates/frontend/src/pages/function/utils.rs
  crates/frontend/src/types.rs
  crates/superposition_types/Cargo.toml
  crates/superposition_types/migrations/2025-03-12-061636_function_types/down.sql
  crates/superposition_types/migrations/2025-03-12-061636_function_types/up.sql
  crates/superposition_types/src/api.rs
  crates/superposition_types/src/api/functions.rs
  crates/superposition_types/src/database/models/cac.rs
  crates/superposition_types/src/database/schema.rs
  docker-compose/postgres/db_init.sql
  workspace_template.sql
Labels: UI, javascript

#442 feat: dependent dimensions
  crates/context_aware_config/src/api/context/helpers.rs
  crates/context_aware_config/src/api/dimension/handlers.rs
  crates/context_aware_config/src/api/dimension/types.rs
  crates/context_aware_config/src/api/dimension/utils.rs
  crates/superposition_types/migrations/2025-03-09-124604_dependent_dimensions/down.sql
  crates/superposition_types/migrations/2025-03-09-124604_dependent_dimensions/up.sql
  crates/superposition_types/src/database/models.rs
  crates/superposition_types/src/database/models/cac.rs
  crates/superposition_types/src/database/schema.rs
  crates/superposition_types/src/database/types.rs
  docker-compose/postgres/db_init.sql
  workspace_template.sql
Labels: P0

#423 feat: Add types for experiment apis in superposition_types
  Cargo.lock
  crates/experimentation_client/Cargo.toml
  crates/experimentation_client/src/lib.rs
  crates/experimentation_client/src/types.rs
  crates/experimentation_platform/src/api/experiments/handlers.rs
  crates/experimentation_platform/src/api/experiments/types.rs
  crates/experimentation_platform/tests/experimentation_tests.rs
  crates/frontend/src/api.rs
  crates/frontend/src/components/context_form/utils.rs
  crates/frontend/src/components/experiment.rs
  crates/frontend/src/components/experiment_conclude_form.rs
  crates/frontend/src/components/experiment_conclude_form/utils.rs
  crates/frontend/src/components/experiment_discard_form.rs
  crates/frontend/src/components/experiment_discard_form/utils.rs
  crates/frontend/src/components/experiment_form.rs
  crates/frontend/src/components/experiment_form/types.rs
  crates/frontend/src/components/experiment_form/utils.rs
  crates/frontend/src/components/experiment_ramp_form.rs
  crates/frontend/src/components/experiment_ramp_form/utils.rs
  crates/frontend/src/logic.rs
  crates/frontend/src/pages/experiment.rs
  crates/frontend/src/pages/experiment_list.rs
  crates/frontend/src/pages/experiment_list/utils.rs
  crates/frontend/src/types.rs
  crates/superposition_derives/src/lib.rs
  crates/superposition_types/src/api.rs
  crates/superposition_types/src/api/experiments.rs
  crates/superposition_types/src/api/functions.rs
  crates/superposition_types/src/custom_query.rs
  crates/superposition_types/src/database.rs
  crates/superposition_types/src/database/models.rs
  crates/superposition_types/src/database/models/experimentation.rs
  makefile
  postman/experimentation-platform.postman_collection.json
  postman/experimentation-platform/Create Experiment 2/event.test.js
  postman/experimentation-platform/Create Experiment/event.test.js
  postman/experimentation-platform/Update Override Keys/event.test.js
Labels: UI, P0, quick win
