Repository juspay/superposition, pull requests merged in 2025-05, with the labels that each got.

#313 Feat/webhook cruds
  clients/generated/smithy/ts/src/Superposition.ts
  clients/generated/smithy/ts/src/SuperpositionClient.ts
  clients/generated/smithy/ts/src/commands/CreateWebhookCommand.ts
  clients/generated/smithy/ts/src/commands/GetWebhookCommand.ts
  clients/generated/smithy/ts/src/commands/ListWebhookCommand.ts
  clients/generated/smithy/ts/src/commands/UpdateWebhookCommand.ts
  clients/generated/smithy/ts/src/commands/index.ts
  clients/generated/smithy/ts/src/models/models_0.ts
  clients/generated/smithy/ts/src/protocols/Aws_restJson1.ts
  crates/experimentation_platform/src/api/experiments/handlers.rs
  crates/service_utils/src/helpers.rs
  crates/superposition/src/main.rs
  crates/superposition/src/webhooks.rs
  crates/superposition/src/webhooks/handlers.rs
  crates/superposition/src/webhooks/helper.rs
  crates/superposition_types/migrations/2024-12-06-112348_webhooks/down.sql
  crates/superposition_types/migrations/2024-12-06-112348_webhooks/up.sql
  crates/superposition_types/src/api.rs
  crates/superposition_types/src/api/webhook.rs
  crates/superposition_types/src/cac/schema.patch
  crates/superposition_types/src/database/models.rs
  crates/superposition_types/src/database/models/others.rs
  crates/superposition_types/src/database/schema.rs
  crates/superposition_types/src/webhook.rs
  docker-compose/postgres/db_init.sql
  smithy/models/main.smithy
  smithy/models/webhook.smithy
  workspace_template.sql
Labels: enhancement

#470 feat: add strict mode support for workspaces
  clients/generated/smithy/ts/src/commands/CreateWorkspaceCommand.ts
  clients/generated/smithy/ts/src/commands/ListWorkspaceCommand.ts
  clients/generated/smithy/ts/src/commands/UpdateWorkspaceCommand.ts
  clients/generated/smithy/ts/src/models/models_0.ts
  clients/generated/smithy/ts/src/protocols/Aws_restJson1.ts
  clients/tests/ts/index.ts
  clients/tests/ts/tests/workspace.test.ts
  crates/context_aware_config/src/api/context/helpers.rs
  crates/context_aware_config/src/api/context/operations.rs
  crates/frontend/src/components/experiment_form.rs
  crates/frontend/src/components/side_nav.rs
  crates/frontend/src/components/workspace_form.rs
  crates/frontend/src/hoc/layout.rs
  crates/frontend/src/pages/context_override.rs
  crates/frontend/src/pages/experiment_list.rs
  crates/frontend/src/pages/organisations.rs
  crates/frontend/src/pages/workspace.rs
  crates/superposition/src/workspace/handlers.rs
  crates/superposition_types/migrations/2025-04-17-053400_limiting_operators/down.sql
  crates/superposition_types/migrations/2025-04-17-053400_limiting_operators/up.sql
  crates/superposition_types/src/api/workspace.rs
  crates/superposition_types/src/database/models.rs
  crates/superposition_types/src/database/superposition_schema.rs
  docker-compose/postgres/db_init.sql
  postman/superposition/Workspace/Create/request.json
  smithy/models/workspace.smithy
Labels: P0, quick win

#497 feat: DefaultConfig type unification and conclude/exp contract fix
  crates/context_aware_config/src/api/default_config.rs
  crates/context_aware_config/src/api/default_config/handlers.rs
  crates/context_aware_config/src/api/default_config/types.rs
  crates/experimentation_platform/src/api/experiments/handlers.rs
  crates/frontend/src/components/default_config_form.rs
  crates/frontend/src/components/default_config_form/types.rs
  crates/frontend/src/components/default_config_form/utils.rs
  crates/frontend/src/pages/default_config.rs
  crates/superposition_types/src/api/default_config.rs
  crates/superposition_types/src/database/models/cac.rs
Labels: P0

#516 fix: Override update/clone/experiment after key filter
  crates/frontend/src/api.rs
  crates/frontend/src/components/experiment_form.rs
  crates/frontend/src/pages/context_override.rs
Labels: bug, priority, P0

#511 feat: Frontend changes for delete experiment
  crates/experimentation_platform/src/api/experiments/cac_api.rs
  crates/experimentation_platform/src/api/experiments/handlers.rs
  crates/frontend/src/api.rs
  crates/frontend/src/components/badge.rs
  crates/frontend/src/components/change_form.rs
  crates/frontend/src/components/context_card.rs
  crates/frontend/src/components/default_config_form.rs
  crates/frontend/src/components/dimension_form.rs
  crates/frontend/src/components/dropdown.rs
  crates/frontend/src/components/experiment.rs
  crates/frontend/src/components/experiment_action_form.rs
  crates/frontend/src/components/experiment_conclude_form.rs
  crates/frontend/src/components/experiment_conclude_form/utils.rs
  crates/frontend/src/components/experiment_discard_form.rs
  crates/frontend/src/components/experiment_form.rs
  crates/frontend/src/components/experiment_form/utils.rs
  crates/frontend/src/components/experiment_ramp_form.rs
  crates/frontend/src/components/function_form.rs
  crates/frontend/src/components/metrics_form.rs
  crates/frontend/src/components/modal.rs
  crates/frontend/src/components/override_form.rs
  crates/frontend/src/components/type_template_form.rs
  crates/frontend/src/components/variant_form.rs
  crates/frontend/src/components/webhook_form.rs
  crates/frontend/src/components/workspace_form.rs
  crates/frontend/src/pages/compare_overrides.rs
  crates/frontend/src/pages/context_override.rs
  crates/frontend/src/pages/experiment.rs
  crates/frontend/src/pages/experiment_list.rs
  crates/frontend/src/pages/home.rs
  crates/frontend/src/schema.rs
  crates/frontend/src/utils.rs
  crates/superposition_types/src/api/experiments.rs
Labels: bug

#529 fix: Function name prefill issue
  crates/frontend/src/pages/default_config.rs
  crates/frontend/src/pages/dimensions.rs
Labels: bug, priority, UI, P0, quick win

#528 fix: List exp behaviour for list all
  crates/experimentation_platform/src/api/experiments/handlers.rs
Labels: enhancement, quick win
