Repository juspay/superposition, pull requests merged in 2025-02, with the labels that each got.

#398 feat: Discard experiment
  clients/js/index.js
  clients/js/src/types.ts
  crates/experimentation_client/src/lib.rs
  crates/experimentation_platform/src/api/experiments/handlers.rs
  crates/experimentation_platform/src/api/experiments/types.rs
  crates/frontend/src/components.rs
  crates/frontend/src/components/experiment.rs
  crates/frontend/src/components/experiment_discard_form.rs
  crates/frontend/src/components/experiment_discard_form/utils.rs
  crates/frontend/src/pages/default_config.rs
  crates/frontend/src/pages/experiment.rs
  crates/frontend/src/pages/experiment_list/utils.rs
  crates/superposition_types/migrations/2025-01-30-094241_add_discard_experiment/down.sql
  crates/superposition_types/migrations/2025-01-30-094241_add_discard_experiment/up.sql
  crates/superposition_types/src/database/models/experimentation.rs
  crates/superposition_types/src/webhook.rs
  docker-compose/postgres/db_init.sql
  postman/experimentation-platform.postman_collection.json
  postman/experimentation-platform/List experiments If-Modified-Since Thu 01 Jan 1970 00_00_00 0000/request.json
  workspace_template.sql
Labels: P0

#395 fix: toggle default value
  crates/frontend/src/components/default_config_form.rs
Labels: bug, UI, P0, quick win

#411 fix: update rust-monaco version
  Cargo.lock
  Dockerfile
  crates/frontend/Cargo.toml
  makefile
Labels: quick win

#409 fix: show delete prompt for delete actions
  crates/frontend/src/components/type_template_form.rs
  crates/frontend/src/pages/custom_types.rs
  crates/frontend/src/pages/default_config.rs
Labels: bug, P0, quick win
